### ISSUE TITLE
YOLO_v3_V4

### ISSUE THREAD

**Issue by asielcabrera** [wvabrinskas/Neuron#15]
hey any recommendation to implement yolov3 with your work?

**Comment by wvabrinskas** [comment]
Oh that's ambitious! I like it. Unfortunately Neuron as of right now doesn't support Convolutions on images so It might be really slow since you have to create an input node for each dimension of each pixel which would be ridiculous. However I am actively working on supporting convolutions and image recognition. Keep an eye out!
